name: Build

on:
  push:
    branches: [fc-palette]
  pull_request:
    branches: [fc-palette]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # Adjust Node version as needed

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build
